fastlane_version "2.120.0"

default_platform :ios

platform :ios do

  desc "Release a new version of ZLogger"
  lane :release do
    # Ensure Git status is clean
    ensure_git_status_clean
    # Ensure Git branch is master
    ensure_git_branch(branch: 'master')
    # Perform Dependency-Manager compatibility tests
    compatibilityTests
    # Perform Tests
    tests
    # Pod push / Pod trunk
    pod_push()
  end

  desc "Increment Version"
  lane :increment do |options|
    # Retrieve Version from options
    version = options[:version]
    # Set Podspec version
    version_bump_podspec(
      path: "ZLogger.podspec",
      version_number: version
    )
    # Set Framework plist version
    set_info_plist_value(
      path: "Configs/ZLogger.plist",
      key: "CFBundleShortVersionString",
      value: version
    )
    # Set Framework Tests plist version
    set_info_plist_value(
      path: "Configs/ZLoggerTests.plist",
      key: "CFBundleShortVersionString",
      value: version
    )
    # Set Example plist version
    set_info_plist_value(
      path: "Example/Resources/Info.plist",
      key: "CFBundleShortVersionString",
      value: version
    )
    # Commit modified files
    git_commit(
        path: [
          "ZLogger.podspec",
          "Configs/ZLogger.plist",
          "Configs/ZLoggerTests.plist",
          "Example/Resources/Info.plist"
        ],
        message: "ZLogger Version #{version} 🚀"
    )
  end

  desc "Runs tests"
  lane :tests do
    # Perform iOS Tests
    scan(
      project: "ZLogger.xcodeproj",
      scheme: "ZLogger-iOS",
      clean: true
    )
    # Perform tvOS Tests
    scan(
      project: "ZLogger.xcodeproj",
      scheme: "ZLogger-tvOS",
      clean: true
    )
    # Perform macOS Tests
    spm(command: "test")
    # Delete SPM build artifacts
    spm(command: "clean")
  end

  desc "Run Dependency-Manager compatibility tests"
  lane :compatibilityTests do
    # Carthage build to ensure Carthage compatibility
    carthage(
      command: "build",
      no_skip_current: true,
      cache_builds: true
    )
    # Pod lib lint to ensure CocoaPods compatibility
    pod_lib_lint(allow_warnings: true)
    # SPM Build to ensure Swift Package Manager compatibility
    spm(command: "build")
    # Delete SPM build artifacts
    spm(command: "clean")
  end

end
